rules:
  property-sort-order: 0
  leading-zero: 0
  no-important: 0
  indentation:
  - 1
  - size: 2
  quotes:
    - 1
    - style: double
  shorthand-values: 0
  no-color-literals: 0
  no-color-keywords: 0
  no-ids: 0
  no-vendor-prefixes: 0
  nesting-depth:
    - 1
    - max-depth: 4