baseURL = "https://discoverthreejs.com/"

languageCode = "en-us"

publishDir = 'public'
contentDir = "markdown"

disableKinds = ["tags", "taxonomy", "taxonomyTerm", "category", "RSS", "robotsTXT"]

enableInlineShortcodes = true

pygmentsCodeFences = true
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = true

linenos = "true"

# use pygments instead of Chroma
# pygmentsUseClassic=true

enableRobotsTXT = false
summaryLength = 240

logFile = "logs.txt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

paginate = 10
paginatePath = "test"

disableHugoGeneratorInject = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Including this causes the build to fail
# https://gohugo.io/variables/site/#the-siteparams-variable
#[params]
#  description = "44"